name: test_case_smena
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.4
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.1.0
  flutter_lints: ^1.0.4
  freezed_annotation: ^2.0.1
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
